import type { ExcalidrawDemoData } from './types';

// Retro-board sketch for the Sprint Retro seed: three colored columns
// (Went Well / Needs Work / Ideas) each with a column header and a couple
// of "sticky note" rectangles. Color-coded #2f9e44 (green) / #e03131 (red)
// / #1971c2 (blue) with matching pale fills for the stickies.

const NOW = 1747000010000;

export const sprintRetroExcalidraw: ExcalidrawDemoData = {
  elements: [
    // ── Column 1: Went Well (green) ───────────────────────────
    {
      id: 'col-well',
      type: 'rectangle',
      x: 50, y: 50, width: 260, height: 400,
      angle: 0,
      strokeColor: '#2f9e44', backgroundColor: 'transparent',
      fillStyle: 'solid', strokeWidth: 2, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: { type: 3 },
      seed: 10001, version: 1, versionNonce: 1000001,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
    },
    {
      id: 'col-well-title',
      type: 'text',
      x: 120, y: 65, width: 120, height: 30,
      angle: 0,
      strokeColor: '#2f9e44', backgroundColor: 'transparent',
      fillStyle: 'solid', strokeWidth: 2, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: null,
      seed: 10002, version: 1, versionNonce: 1000002,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
      text: 'Went Well', fontSize: 22, fontFamily: 1,
      textAlign: 'center', verticalAlign: 'middle',
      containerId: null, originalText: 'Went Well',
      autoResize: true, lineHeight: 1.25,
    },
    {
      id: 'col-well-note-1',
      type: 'rectangle',
      x: 80, y: 120, width: 200, height: 60,
      angle: 0,
      strokeColor: '#2f9e44', backgroundColor: '#d3f9d8',
      fillStyle: 'solid', strokeWidth: 1, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: { type: 3 },
      seed: 10003, version: 1, versionNonce: 1000003,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
    },
    {
      id: 'col-well-note-1-text',
      type: 'text',
      x: 90, y: 135, width: 180, height: 30,
      angle: 0,
      strokeColor: '#1e1e1e', backgroundColor: 'transparent',
      fillStyle: 'solid', strokeWidth: 1, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: null,
      seed: 10004, version: 1, versionNonce: 1000004,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
      text: 'Money-Shot live', fontSize: 16, fontFamily: 1,
      textAlign: 'center', verticalAlign: 'middle',
      containerId: null, originalText: 'Money-Shot live',
      autoResize: true, lineHeight: 1.25,
    },
    {
      id: 'col-well-note-2',
      type: 'rectangle',
      x: 80, y: 200, width: 200, height: 60,
      angle: 0,
      strokeColor: '#2f9e44', backgroundColor: '#d3f9d8',
      fillStyle: 'solid', strokeWidth: 1, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: { type: 3 },
      seed: 10005, version: 1, versionNonce: 1000005,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
    },
    {
      id: 'col-well-note-2-text',
      type: 'text',
      x: 90, y: 215, width: 180, height: 30,
      angle: 0,
      strokeColor: '#1e1e1e', backgroundColor: 'transparent',
      fillStyle: 'solid', strokeWidth: 1, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: null,
      seed: 10006, version: 1, versionNonce: 1000006,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
      text: 'Bus contract held', fontSize: 16, fontFamily: 1,
      textAlign: 'center', verticalAlign: 'middle',
      containerId: null, originalText: 'Bus contract held',
      autoResize: true, lineHeight: 1.25,
    },

    // ── Column 2: Needs Work (red) ────────────────────────────
    {
      id: 'col-work',
      type: 'rectangle',
      x: 340, y: 50, width: 260, height: 400,
      angle: 0,
      strokeColor: '#e03131', backgroundColor: 'transparent',
      fillStyle: 'solid', strokeWidth: 2, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: { type: 3 },
      seed: 20001, version: 1, versionNonce: 2000001,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
    },
    {
      id: 'col-work-title',
      type: 'text',
      x: 410, y: 65, width: 120, height: 30,
      angle: 0,
      strokeColor: '#e03131', backgroundColor: 'transparent',
      fillStyle: 'solid', strokeWidth: 2, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: null,
      seed: 20002, version: 1, versionNonce: 2000002,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
      text: 'Needs Work', fontSize: 22, fontFamily: 1,
      textAlign: 'center', verticalAlign: 'middle',
      containerId: null, originalText: 'Needs Work',
      autoResize: true, lineHeight: 1.25,
    },
    {
      id: 'col-work-note-1',
      type: 'rectangle',
      x: 370, y: 120, width: 200, height: 60,
      angle: 0,
      strokeColor: '#e03131', backgroundColor: '#ffe3e3',
      fillStyle: 'solid', strokeWidth: 1, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: { type: 3 },
      seed: 20003, version: 1, versionNonce: 2000003,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
    },
    {
      id: 'col-work-note-1-text',
      type: 'text',
      x: 380, y: 135, width: 180, height: 30,
      angle: 0,
      strokeColor: '#1e1e1e', backgroundColor: 'transparent',
      fillStyle: 'solid', strokeWidth: 1, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: null,
      seed: 20004, version: 1, versionNonce: 2000004,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
      text: 'NF cache poisoning', fontSize: 16, fontFamily: 1,
      textAlign: 'center', verticalAlign: 'middle',
      containerId: null, originalText: 'NF cache poisoning',
      autoResize: true, lineHeight: 1.25,
    },
    {
      id: 'col-work-note-2',
      type: 'rectangle',
      x: 370, y: 200, width: 200, height: 60,
      angle: 0,
      strokeColor: '#e03131', backgroundColor: '#ffe3e3',
      fillStyle: 'solid', strokeWidth: 1, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: { type: 3 },
      seed: 20005, version: 1, versionNonce: 2000005,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
    },
    {
      id: 'col-work-note-2-text',
      type: 'text',
      x: 380, y: 215, width: 180, height: 30,
      angle: 0,
      strokeColor: '#1e1e1e', backgroundColor: 'transparent',
      fillStyle: 'solid', strokeWidth: 1, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: null,
      seed: 20006, version: 1, versionNonce: 2000006,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
      text: 'Svelte share map', fontSize: 16, fontFamily: 1,
      textAlign: 'center', verticalAlign: 'middle',
      containerId: null, originalText: 'Svelte share map',
      autoResize: true, lineHeight: 1.25,
    },

    // ── Column 3: Ideas (blue) ────────────────────────────────
    {
      id: 'col-ideas',
      type: 'rectangle',
      x: 630, y: 50, width: 260, height: 400,
      angle: 0,
      strokeColor: '#1971c2', backgroundColor: 'transparent',
      fillStyle: 'solid', strokeWidth: 2, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: { type: 3 },
      seed: 30001, version: 1, versionNonce: 3000001,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
    },
    {
      id: 'col-ideas-title',
      type: 'text',
      x: 720, y: 65, width: 80, height: 30,
      angle: 0,
      strokeColor: '#1971c2', backgroundColor: 'transparent',
      fillStyle: 'solid', strokeWidth: 2, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: null,
      seed: 30002, version: 1, versionNonce: 3000002,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
      text: 'Ideas', fontSize: 22, fontFamily: 1,
      textAlign: 'center', verticalAlign: 'middle',
      containerId: null, originalText: 'Ideas',
      autoResize: true, lineHeight: 1.25,
    },
    {
      id: 'col-ideas-note-1',
      type: 'rectangle',
      x: 660, y: 120, width: 200, height: 60,
      angle: 0,
      strokeColor: '#1971c2', backgroundColor: '#d0ebff',
      fillStyle: 'solid', strokeWidth: 1, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: { type: 3 },
      seed: 30003, version: 1, versionNonce: 3000003,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
    },
    {
      id: 'col-ideas-note-1-text',
      type: 'text',
      x: 670, y: 135, width: 180, height: 30,
      angle: 0,
      strokeColor: '#1e1e1e', backgroundColor: 'transparent',
      fillStyle: 'solid', strokeWidth: 1, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: null,
      seed: 30004, version: 1, versionNonce: 3000004,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
      text: 'Solid.js remote?', fontSize: 16, fontFamily: 1,
      textAlign: 'center', verticalAlign: 'middle',
      containerId: null, originalText: 'Solid.js remote?',
      autoResize: true, lineHeight: 1.25,
    },
  ],
  appState: {
    viewBackgroundColor: '#ffffff',
    gridSize: 20,
    gridStep: 5,
    gridModeEnabled: false,
  },
};
