import type { ExcalidrawDemoData } from './types';

// UI wireframe sketch for the Design Sync seed: a classic web-app shell
// — top header bar, left nav sidebar, main content area with two cards
// stacked above a wide content panel. Plain neutral palette (no brand
// accent) so it reads as "design canvas in progress".

const NOW = 1747000020000;

export const designSyncExcalidraw: ExcalidrawDemoData = {
  elements: [
    // Header bar
    {
      id: 'wf-header',
      type: 'rectangle',
      x: 50, y: 40, width: 760, height: 60,
      angle: 0,
      strokeColor: '#1e1e1e', backgroundColor: '#e9ecef',
      fillStyle: 'solid', strokeWidth: 2, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: { type: 3 },
      seed: 50001, version: 1, versionNonce: 5000001,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
    },
    {
      id: 'wf-header-text',
      type: 'text',
      x: 80, y: 58, width: 100, height: 25,
      angle: 0,
      strokeColor: '#1e1e1e', backgroundColor: 'transparent',
      fillStyle: 'solid', strokeWidth: 2, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: null,
      seed: 50002, version: 1, versionNonce: 5000002,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
      text: 'Header', fontSize: 20, fontFamily: 1,
      textAlign: 'left', verticalAlign: 'middle',
      containerId: null, originalText: 'Header',
      autoResize: true, lineHeight: 1.25,
    },

    // Sidebar
    {
      id: 'wf-nav',
      type: 'rectangle',
      x: 50, y: 120, width: 180, height: 360,
      angle: 0,
      strokeColor: '#1e1e1e', backgroundColor: '#f1f3f5',
      fillStyle: 'solid', strokeWidth: 2, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: { type: 3 },
      seed: 50003, version: 1, versionNonce: 5000003,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
    },
    {
      id: 'wf-nav-text',
      type: 'text',
      x: 110, y: 140, width: 60, height: 25,
      angle: 0,
      strokeColor: '#1e1e1e', backgroundColor: 'transparent',
      fillStyle: 'solid', strokeWidth: 2, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: null,
      seed: 50004, version: 1, versionNonce: 5000004,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
      text: 'Nav', fontSize: 20, fontFamily: 1,
      textAlign: 'center', verticalAlign: 'middle',
      containerId: null, originalText: 'Nav',
      autoResize: true, lineHeight: 1.25,
    },
    // Nav items (small lines suggesting list)
    {
      id: 'wf-nav-item-1',
      type: 'rectangle',
      x: 70, y: 200, width: 140, height: 30,
      angle: 0,
      strokeColor: '#868e96', backgroundColor: 'transparent',
      fillStyle: 'solid', strokeWidth: 1, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: { type: 3 },
      seed: 50005, version: 1, versionNonce: 5000005,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
    },
    {
      id: 'wf-nav-item-2',
      type: 'rectangle',
      x: 70, y: 250, width: 140, height: 30,
      angle: 0,
      strokeColor: '#868e96', backgroundColor: 'transparent',
      fillStyle: 'solid', strokeWidth: 1, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: { type: 3 },
      seed: 50006, version: 1, versionNonce: 5000006,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
    },
    {
      id: 'wf-nav-item-3',
      type: 'rectangle',
      x: 70, y: 300, width: 140, height: 30,
      angle: 0,
      strokeColor: '#868e96', backgroundColor: 'transparent',
      fillStyle: 'solid', strokeWidth: 1, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: { type: 3 },
      seed: 50007, version: 1, versionNonce: 5000007,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
    },

    // Main content area
    {
      id: 'wf-main',
      type: 'rectangle',
      x: 250, y: 120, width: 560, height: 360,
      angle: 0,
      strokeColor: '#1e1e1e', backgroundColor: 'transparent',
      fillStyle: 'solid', strokeWidth: 2, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: { type: 3 },
      seed: 50008, version: 1, versionNonce: 5000008,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
    },

    // Card 1 (top-left)
    {
      id: 'wf-card-1',
      type: 'rectangle',
      x: 280, y: 150, width: 250, height: 140,
      angle: 0,
      strokeColor: '#1e1e1e', backgroundColor: '#fff9db',
      fillStyle: 'solid', strokeWidth: 2, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: { type: 3 },
      seed: 50009, version: 1, versionNonce: 5000009,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
    },
    {
      id: 'wf-card-1-text',
      type: 'text',
      x: 360, y: 210, width: 90, height: 25,
      angle: 0,
      strokeColor: '#1e1e1e', backgroundColor: 'transparent',
      fillStyle: 'solid', strokeWidth: 2, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: null,
      seed: 50010, version: 1, versionNonce: 5000010,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
      text: 'Card 1', fontSize: 20, fontFamily: 1,
      textAlign: 'center', verticalAlign: 'middle',
      containerId: null, originalText: 'Card 1',
      autoResize: true, lineHeight: 1.25,
    },

    // Card 2 (top-right)
    {
      id: 'wf-card-2',
      type: 'rectangle',
      x: 550, y: 150, width: 240, height: 140,
      angle: 0,
      strokeColor: '#1e1e1e', backgroundColor: '#fff9db',
      fillStyle: 'solid', strokeWidth: 2, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: { type: 3 },
      seed: 50011, version: 1, versionNonce: 5000011,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
    },
    {
      id: 'wf-card-2-text',
      type: 'text',
      x: 625, y: 210, width: 90, height: 25,
      angle: 0,
      strokeColor: '#1e1e1e', backgroundColor: 'transparent',
      fillStyle: 'solid', strokeWidth: 2, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: null,
      seed: 50012, version: 1, versionNonce: 5000012,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
      text: 'Card 2', fontSize: 20, fontFamily: 1,
      textAlign: 'center', verticalAlign: 'middle',
      containerId: null, originalText: 'Card 2',
      autoResize: true, lineHeight: 1.25,
    },

    // Bottom content panel
    {
      id: 'wf-content',
      type: 'rectangle',
      x: 280, y: 310, width: 510, height: 150,
      angle: 0,
      strokeColor: '#1e1e1e', backgroundColor: '#f8f9fa',
      fillStyle: 'solid', strokeWidth: 2, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: { type: 3 },
      seed: 50013, version: 1, versionNonce: 5000013,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
    },
    {
      id: 'wf-content-text',
      type: 'text',
      x: 490, y: 375, width: 100, height: 25,
      angle: 0,
      strokeColor: '#1e1e1e', backgroundColor: 'transparent',
      fillStyle: 'solid', strokeWidth: 2, strokeStyle: 'solid',
      roughness: 1, opacity: 100,
      groupIds: [], frameId: null, roundness: null,
      seed: 50014, version: 1, versionNonce: 5000014,
      isDeleted: false, boundElements: null, updated: NOW,
      link: null, locked: false,
      text: 'Content', fontSize: 20, fontFamily: 1,
      textAlign: 'center', verticalAlign: 'middle',
      containerId: null, originalText: 'Content',
      autoResize: true, lineHeight: 1.25,
    },
  ],
  appState: {
    viewBackgroundColor: '#ffffff',
    gridSize: 20,
    gridStep: 5,
    gridModeEnabled: false,
  },
};
