#!/usr/bin/env node
import {
  readFileSync,
  writeFileSync,
  rmSync,
  cpSync,
  mkdirSync,
  copyFileSync,
} from 'node:fs';
import { createHash } from 'node:crypto';
import { execSync } from 'node:child_process';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const sh = (cmd) => {
  console.log(`\n[build-deploy] $ ${cmd}`);
  execSync(cmd, { cwd: repoRoot, stdio: 'inherit' });
};

const sriConstantsPath = resolve(
  repoRoot,
  'packages/shell/src/generated/sri-constants.ts',
);
const sriStub = readFileSync(sriConstantsPath, 'utf8');
const restoreStub = () => writeFileSync(sriConstantsPath, sriStub);

const sha384 = (bytes) =>
  'sha384-' + createHash('sha384').update(bytes).digest('base64');

const writeSriConstants = ({ enabled, manifest, host }) => {
  writeFileSync(
    sriConstantsPath,
    `// AUTO-GENERATED by scripts/build-deploy.mjs — do not edit.
// The committed stub is restored in a \`finally\` block after the prod
// build (or recover manually via
// \`git checkout packages/shell/src/generated/sri-constants.ts\`).
export const sriEnabled = ${enabled};
export const manifestIntegrity = ${JSON.stringify(manifest)};
export const hostRemoteEntryIntegrity = ${JSON.stringify(host)};
`,
  );
};

try {
  sh('pnpm -F shell clean');
  sh('pnpm -F whiteboard clean');
  sh('pnpm -F mermaid clean');

  // Remotes first — the shell needs their remoteEntry.json hashes to seed
  // the prod manifest, and the prod manifest hash to bake into main.ts.
  sh('pnpm -F whiteboard build:standalone');
  sh('pnpm -F whiteboard build:federate');
  sh('pnpm -F mermaid build:standalone');
  sh('pnpm -F mermaid build:federate');

  const whiteboardRemoteEntry = readFileSync(
    resolve(repoRoot, 'packages/whiteboard/dist/remoteEntry.json'),
  );
  const mermaidRemoteEntry = readFileSync(
    resolve(repoRoot, 'packages/mermaid/dist/remoteEntry.json'),
  );
  const whiteboardIntegrity = sha384(whiteboardRemoteEntry);
  const mermaidIntegrity = sha384(mermaidRemoteEntry);

  // Compose the prod manifest once in memory; the same bytes are hashed
  // and later written into dist/deploy/.
  // The `./` prefix is load-bearing — `es-module-shims` treats bare
  // strings as bare specifiers and refuses to resolve them. See
  // `docs/deployment.md` → "Why the `./` prefix matters".
  const manifestObject = {
    whiteboard: {
      url: './whiteboard/remoteEntry.json',
      integrity: whiteboardIntegrity,
    },
    mermaid: {
      url: './mermaid/remoteEntry.json',
      integrity: mermaidIntegrity,
    },
  };
  const manifestBytes = Buffer.from(
    JSON.stringify(manifestObject, null, 2) + '\n',
    'utf8',
  );
  const manifestSri = sha384(manifestBytes);

  // Pass 1: SRI disabled. Produces the shell's remoteEntry.json so we can
  // hash it before pass 2 bakes that hash into main.ts.
  writeSriConstants({ enabled: false, manifest: '', host: '' });
  sh('pnpm -F shell build:deploy');

  const hostRemoteEntryPath = resolve(
    repoRoot,
    'packages/shell/dist/shell/browser/remoteEntry.json',
  );
  const hostBytes1 = readFileSync(hostRemoteEntryPath);
  const hostIntegrity = sha384(hostBytes1);

  // Pass 2: bake in both hashes. The shell's remoteEntry.json must be
  // byte-identical to pass 1 — shared-chunk filenames are content-hashed
  // and unaffected by main.ts content. The sanity check below catches any
  // drift (which would mean the host integrity hash is invalid).
  writeSriConstants({
    enabled: true,
    manifest: manifestSri,
    host: hostIntegrity,
  });
  sh('pnpm -F shell build:deploy');

  const hostBytes2 = readFileSync(hostRemoteEntryPath);
  if (sha384(hostBytes2) !== hostIntegrity) {
    throw new Error(
      '[build-deploy] FATAL: shell remoteEntry.json drifted between pass 1 and pass 2 — host SRI hash would be invalid. The byte-stability assumption is broken; rework the injection mechanism.',
    );
  }

  const deployRoot = resolve(repoRoot, 'dist/deploy');
  rmSync(deployRoot, { recursive: true, force: true });
  mkdirSync(deployRoot, { recursive: true });

  cpSync(
    resolve(repoRoot, 'packages/shell/dist/shell/browser'),
    deployRoot,
    { recursive: true, force: true },
  );
  cpSync(
    resolve(repoRoot, 'packages/whiteboard/dist'),
    resolve(deployRoot, 'whiteboard'),
    { recursive: true, force: true },
  );
  cpSync(
    resolve(repoRoot, 'packages/mermaid/dist'),
    resolve(deployRoot, 'mermaid'),
    { recursive: true, force: true },
  );

  // Overwrite the manifest copied from packages/shell/public/ (dev-shape
  // http://localhost URLs) with the prod object-shape bytes whose hash is
  // baked into main.ts.
  writeFileSync(
    resolve(deployRoot, 'federation.manifest.json'),
    manifestBytes,
  );

  const manifestOnDisk = readFileSync(
    resolve(deployRoot, 'federation.manifest.json'),
  );
  if (sha384(manifestOnDisk) !== manifestSri) {
    throw new Error(
      '[build-deploy] FATAL: federation.manifest.json on disk does not match the bytes hashed for manifestIntegrity.',
    );
  }

  // Remote build.mjs scripts treat public/ as dev-server read-through and
  // don't emit dist/index.html. Copy each remote's standalone HTML into
  // the assembled tree so /<subpath>/whiteboard/ and /<subpath>/mermaid/
  // resolve to the standalone bundle.
  copyFileSync(
    resolve(repoRoot, 'packages/whiteboard/public/index.html'),
    resolve(deployRoot, 'whiteboard/index.html'),
  );
  copyFileSync(
    resolve(repoRoot, 'packages/mermaid/public/index.html'),
    resolve(deployRoot, 'mermaid/index.html'),
  );

  console.log('\n[build-deploy] dist/deploy/ ready (SRI enabled).');
  console.log(`[build-deploy]   manifest:           ${manifestSri}`);
  console.log(`[build-deploy]   host remoteEntry:   ${hostIntegrity}`);
  console.log(`[build-deploy]   whiteboard remote:  ${whiteboardIntegrity}`);
  console.log(`[build-deploy]   mermaid remote:     ${mermaidIntegrity}`);
  console.log('[build-deploy] Smoke-serve recipe (subpath via parent dir):');
  console.log('  mv dist/deploy dist/frankenstein-meeting-room');
  console.log('  npx serve dist -p 8088');
  console.log('  open http://localhost:8088/frankenstein-meeting-room/');
} finally {
  restoreStub();
}
